name: "sample react ci pipeline"
on:
    push:
        branches:
            - main
            - master
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: "setup node js"
              uses: actions/setup-node@v4
              with:
                node-version: '21'
                
            - name: "check node version"
              run: node --version

            - name: "clone github repo"
              uses: actions/checkout@v2
            - name: "install dependencies"

              run: npm install
            - name: "list directories"
              run: ls

            - name: "run test"
              run: npm test

            - name: "run build"
              run: npm run build
                
            
